### ISSUE TITLE
Bill of materials? 

### ISSUE THREAD

**Issue by elasticdotventures** [christophjurczyk/ATmega64M1-Development-Board#2]
Hi @christophjurczyk 

Very interesting project. Did I miss an included bill of materials (purchasing list) or way to order & assemble one of these? 
I'd very much like to put together a few and do some testing. 

I'm developing "GrowPotBot" an ESP32 Can AI indoor garden appliance that will use CAN connected Arduino (or possibly STM32F04) sensors & relays.   The goal is to have the various subsystems coordinate using openCAN and I'm hoping to engage the maker community by having a straightforward Arduino interface with a few extra GPIO's and Analog channels for "other things" people might want to connect to the same system.

I'm trying to re-invent as few technologies as necessary and only use well documented non-patent encumbered open systems. 

Let me know if you're interested in collaborating, mentoring or available for hire.  
Thanks!

**Comment by christophjurczyk** [comment]
Hi @elasticdotventures 

Happy to hear that you're interested in the board. Sorry for the late replay. As I saw you collected all parts for a BOM. By the way here is my BOM:


Qty | Value | Device | Package | Parts | Vendor | Pcs/Order | Price/Order | Price/PCB
-- | -- | -- | -- | -- | -- | -- | -- | --
1 |   | 10-XX | B3F-10XX | S1 | Aliexpress | 10 | 0.32 € | 0.03 €
1 |   | F09HP | F09HP | X1 | Aliexpress | 5 | 0.91 € | 0.18 €
6 |   | FE08-1 | FE08 | SV2, SV3, SV4,   SV5, SV6, SV7 | Aliexpress | 10 | 1.05 € | 0.63 €
1 |   | JP1E | JP1 | JP1 | Aliexpress | 10 | 0.70 € | 0.07 €
3 |   | JP2E | JP2 | JP2, JP3, JP4 | Aliexpress | 10 | 0.70 € | 0.21 €
6 |   | LEDSML0805 | SML0805 | LED1, LED2, LED3, LED4, LED5, LED6 | Aliexpress | 100 | 0.87 € | 0.05 €
1 |   | ML6 | ML6 | SV1 | Aliexpress | 10 | 0.83 € | 0.08 €
1 |   | PTCFUSE-1206 | R1206 | F1 | Aliexpress | 100 | 2.10 € | 0.02 €
1 |   | USB | USB-MICRO-SMD_WITHOUT_PASTE | U2 | optional | 1 |   | -   €
1 |   | USB-B-H | USB-B-H | X2 | Aliexpress | 10 | 0.91 € | 0.09 €
9 | 100n | C-EUC0603 | C0603 | C6, C8, C10,   C13, C14, C16, C17, C18, C19 | Aliexpress | 100 | 0.97 € | 0.09 €
1 | 10k | R-EU_M0805 | M0805 | R3 | Aliexpress | 100 | 0.69 € | 0.01 €
8 | 10u | CPOL-EUA/3216-18W | A/3216-18W | C1, C2, C3, C4,   C5, C7, C12, C15 | Aliexpress | 10 | 0.69 € | 0.55 €
1 | 120 | R-EU_M0805 | M0805 | R7 | Aliexpress | 100 | 0.69 € | 0.01 €
1 | 16M | CRYSTALHC49S | HC49/S | Q1 | Aliexpress | 10 | 0.65 € | 0.07 €
6 | 1k | R-EU_M0805 | M0805 | R1, R2, R4, R5, R8, R9 | Aliexpress | 100 | 0.69 € | 0.04 €
2 | 22p | C-EUC0603 | C0603 | C9, C11 | Aliexpress | 100 | 0.85 € | 0.02 €
1 | 47k | R-EU_M0805 | M0805 | R6 | Aliexpress | 100 | 0.69 € | 0.01 €
1 | ADM3053M | ADM3053M | SO20W | IC3 | optional | 1 |   | -   €
1 | ATMEGA64M1 | ATMEGA64M1 | QFN-32 | IC11 | Aliexpress | 3 | 15.79 € | 5.26 €
1 | DCJ0202 | DCJ0202 | DCJ0202 | J1 | Aliexpress | 10 | 0.53 € | 0.05 €
1 | FT232RL | FT232RL | SSOP28 | IC4 | Aliexpress | 1 | 1.26 € | 1.26 €
1 | LM1117IMPX-3.3 | LM1117IMPX-3.3 | SOT223 | IC1 | Aliexpress | 10 | 0.24 € | 0.02 €
1 | LM1117IMPX-5.0 | LM1117IMPX-5.0 | SOT223 | IC2 | Aliexpress | 10 | 0.34 € | 0.03 €
1 | MCP2562 | MCP2562 | DFN3X3 | U1 | distrelec | 1 | 1.05 € | 1.05 €
1 |   | PCB |   |   | JLCPCB | 10 | 11.21 € | 1.12 €
  |   |   |   |   |   |   | Price/PCB: | 10.96   €

Best Regards,
Christoph
